objects/ADR_Proveedor__c/ADR_Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ADR_Proveedor__c/fields/ADR_Fecha_Entrega__c.field-meta.xml
<CustomField>
    <fullName>ADR_Fecha_Entrega__c</fullName>
    <label>Fecha Entrega</label>
    <type>Date</type>
</CustomField>

objects/ADR_Proveedor__c/fields/ADR_Localizacion__c.field-meta.xml
<CustomField>
    <fullName>ADR_Localizacion__c</fullName>
    <label>Localizacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centro</fullName>
            </value>
            <value>
                <fullName>Norte</fullName>
            </value>
            <value>
                <fullName>Sur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ADR_Proveedor__c/fields/ADR_Producto__c.field-meta.xml
<CustomField>
    <fullName>ADR_Producto__c</fullName>
    <label>Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/ADR_Proveedor__c/fields/ADR_Tienda__c.field-meta.xml
<CustomField>
    <fullName>ADR_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>ADR_Tienda__c</referenceTo>
    <relationshipLabel>Proveedores</relationshipLabel>
    <relationshipName>Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

classes/ADR_InformacionProveedor.cls
public class ADR_InformacionProveedor {
    Public void DetallesProveedor(){
        for(ADR_Proveedor__c objProveedor: [SELECT Name,ADR_Producto__c, ADR_Fecha_Entrega__c, ADR_Tienda__r.Name, ADR_Localizacion__c FROM ADR_Proveedor__c]){
    		System.debug('Proveedor:'+objProveedor.name+'\nProducto:'+objProveedor.ADR_Producto__c+'\nFecha de Entrega:'+objProveedor.ADR_Fecha_Entrega__c+'\nTienda:'+objProveedor.ADR_Tienda__r.Name+'\nLocalización:'+objProveedor.ADR_Localizacion__c);
		}  
    }
    public void ProveedorTienda(){
       	Map<String, String> mapProveedor= new Map<String,String>();
        for(ADR_Proveedor__c objProveedor:[SELECT Name,ADR_Tienda__r.Id FROM ADR_Proveedor__c]){
				mapProveedor.put(objProveedor.Id,objProveedor.name);
		}
        System.debug('mapProveedor-->'+mapProveedor);
    }
}