objects/ADR_Proveedor__c/ADR_Proveedor__c.object-meta.xml
<CustomObject>
    <label>Proveedor</label>
    <nameField>
        <label>Proveedor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proveedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ADR_Proveedor__c/fields/ADR_Fecha_Entrega__c.field-meta.xml
<CustomField>
    <fullName>ADR_Fecha_Entrega__c</fullName>
    <label>Fecha Entrega</label>
    <type>Date</type>
</CustomField>

objects/ADR_Proveedor__c/fields/ADR_Localizacion__c.field-meta.xml
<CustomField>
    <fullName>ADR_Localizacion__c</fullName>
    <label>Localizacion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centro</fullName>
            </value>
            <value>
                <fullName>Norte</fullName>
            </value>
            <value>
                <fullName>Sur</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/ADR_Proveedor__c/fields/ADR_Producto__c.field-meta.xml
<CustomField>
    <fullName>ADR_Producto__c</fullName>
    <label>Producto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

objects/ADR_Proveedor__c/fields/ADR_Tienda__c.field-meta.xml
<CustomField>
    <fullName>ADR_Tienda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tienda</label>
    <referenceTo>ADR_Tienda__c</referenceTo>
    <relationshipLabel>Proveedores</relationshipLabel>
    <relationshipName>Proveedores</relationshipName>
    <type>Lookup</type>
</CustomField>

AbdulAviñaVidaña/classes/ADR_informacionProveedor.cls
public class ADR_informacionProveedor {

    public void detallesProveedor(){
		for(ADR_Proveedor__c objProveedor: [SELECT ADR_Producto__c, ADR_Fecha_Entrega__c, ADR_Tienda__r.Name, 	ADR_Localizacion__c FROM ADR_Proveedor__c]){
		system.debug('\nProducto: '+objProveedor.ADR_Producto__c+'\nFecha Entrega: '+objProveedor.ADR_Fecha_Entrega__c+'\nTienda: '+objProveedor.ADR_Tienda__r.Name+'\nLocalizacion: '+objProveedor.ADR_Localizacion__c); 
    
		}
    }
    
    public void proveedorTienda(){
        Map<Id, ADR_Proveedor__c> mapProveedor= new Map<Id, ADR_Proveedor__c>();
        for(ADR_Proveedor__c objProveedor: [SELECT ADR_Tienda__r.Id, ADR_Producto__c, ADR_Localizacion__c, ADR_Fecha_Entrega__c FROM ADR_Proveedor__c LIMIT 1]){
           mapProveedor.put(objProveedor.ADR_Tienda__r.Id,objProveedor);
		system.debug('\nTienda id--datos proveedor: '+mapProveedor); 
    
		}
    }
}